source:
	fpc source.pas -Tlinux -Mobjfpc && mv source bin && ./bin && ~/Загрузки/gephi/bin/gephi graph.csv

def:
	fpc $(file).pas -Tlinux -Mobjfpc && mv $(file) bin && ./bin && ~/Загрузки/gephi/bin/gephi graph.csv